apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-pv
          persistentVolumeClaim:
            claimName: db-pvc
      restartPolicy: Always 
      containers:
      - name: db
        image: postgres:alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-conf
        - secretRef:
            name: db-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-pv
          
