apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gitea
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db:5432
            - name: DB_NAME
              value: gitea
            - name: DB_PASSWD
              value: gitea
            - name: DB_TYPE
              value: postgres
            - name: DB_USER
              value: gitea
          image: gitea/gitea:latest
          name: gitea
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: git-data
      restartPolicy: Always
      volumes:
        - name: git-data
          persistentVolumeClaim:
            claimName: git-data
status: {}
