apiVersion: v1
kind: Pod
metadata:
  name: readinesspod
  labels:
    name: readinesspod
spec:
  securityContext:
    runAsUser: 1000
  restartPolicy: Never
  containers:
  - name: readiness
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    # args:
    #   - /bin/sh
    #   - -c
    #   - touch /tmp/healthy; sleep infinity;
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
