apiVersion: v1
kind: Pod
metadata:
  name: livenesspod
  labels:
    name: livenesspod
spec:
  containers:
  - name: liveness
    image: busybox:latest
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep infinity;
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    livenessProbe:
      exec: # tcpSocket, hpptGet ...
        command: 
          - cat 
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

    
