# k create serviceaccount namaste
apiVersion: v1
kind: Pod
metadata:
  name: sapod
  labels:
    name: sapod
spec:
  serviceAccountName: mysa
  containers:
  - name: sapod
    image: bitnami/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
