apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: al-pod
  name: al-pod
spec:
  containers:
  - env:
    - name: AL_USER
      valueFrom:
        configMapKeyRef:
          key: AL_USER
          name: al-config
    - name: REDIS_PASSWORD
      value: "password"
    image: bitnami/redis
    name: al-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
