# k create secret generic db-secret --from-literal=MYSQL_ROOT_PASSWORD=YoYoSecret --from-literal=MYSQL_PASSWORD=XoXoPassword
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_PASSWORD: WG9Yb1Bhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: WW9Zb1NlY3JldA==

