apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-stateful
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath: 
    path: /data/db-pv-stateful
